-- =============================================================================
-- Batches restructure - Phase 3d (SWITCH) - ROLLBACK
-- Date: 2026-09-29
--
-- Puts the batches back exactly as they were just before
-- 2026-09-29_batches_phase3d_switch.sql ran, using the backup tables that
-- file created in migration_backup:
--   - re-creates the deleted per-subject batch rows (same ids) and batches.subject_id
--   - points every backed-up exam to its old batch row
--   - removes the new constraints and restores the old ones
--   - restores subject_batches to its backed-up rows
-- Rows created AFTER the switch (new batches, links or exams) are kept.
--
-- Run this only if asked to undo the switch.
-- Run in: Supabase -> SQL Editor -> New query -> Run
-- =============================================================================

begin;

do $$
begin
  if not exists (select 1 from information_schema.tables
                 where table_schema = 'migration_backup' and table_name = 'batches_before_switch') then
    raise exception 'Backup of the switch is missing (migration_backup.batches_before_switch)';
  end if;
  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'batches' and column_name = 'subject_id') then
    raise exception 'batches.subject_id exists: the switch is not in place, nothing to undo';
  end if;
end $$;

-- New constraints off
alter table public.exams drop constraint exams_subject_batch_fkey;
alter table public.exams alter column subject_id drop not null;
alter table public.exams alter column batch_id drop not null;
alter table public.batches drop constraint batches_slug_not_empty;
drop index public.batches_graduation_year_key;
drop index public.batches_slug_key;

-- batches.subject_id back, with its original foreign key
alter table public.batches
  add column subject_id uuid references public.subjects(id) on delete cascade;

-- Deleted rows back (same ids); slug is generated by the database from the name
insert into public.batches (id, subject_id, name, description, display_order,
                            created_at, updated_at, graduation_year)
select x.id, x.subject_id, x.name, x.description, x.display_order,
       x.created_at, x.updated_at, x.graduation_year
from migration_backup.batches_before_switch x
where not exists (select 1 from public.batches b where b.id = x.id);

update public.batches b
set subject_id = x.subject_id
from migration_backup.batches_before_switch x
where x.id = b.id;

create unique index batches_subject_slug_uniq on public.batches (subject_id, slug);

-- Exams back to their old batch rows
update public.exams e
set batch_id = x.batch_id
from migration_backup.exams_batch_before_switch x
where x.id = e.id and e.batch_id is distinct from x.batch_id;

-- Original foreign key: exams follow their batch row
alter table public.exams drop constraint exams_batch_id_fkey;
alter table public.exams
  add constraint exams_batch_id_fkey
  foreign key (batch_id) references public.batches(id) on delete cascade;

-- subject_batches back to its backed-up rows
delete from public.subject_batches sb
where not exists (select 1 from migration_backup.subject_batches_before_switch x where x.id = sb.id);

insert into public.subject_batches (id, subject_id, batch_id, created_at)
select x.id, x.subject_id, x.batch_id, x.created_at
from migration_backup.subject_batches_before_switch x
where not exists (select 1 from public.subject_batches sb where sb.id = x.id)
on conflict do nothing;

-- Self-checks
do $$
declare
  v_missing_batches int;
  v_wrong_exams     int;
begin
  select count(*) into v_missing_batches
  from migration_backup.batches_before_switch x
  where not exists (select 1 from public.batches b where b.id = x.id and b.subject_id is not distinct from x.subject_id);

  select count(*) into v_wrong_exams
  from migration_backup.exams_batch_before_switch x
  join public.exams e on e.id = x.id
  where e.batch_id is distinct from x.batch_id;

  if v_missing_batches > 0 then
    raise exception '% batch row(s) were not restored', v_missing_batches;
  end if;
  if v_wrong_exams > 0 then
    raise exception '% exam(s) were not restored to their batch', v_wrong_exams;
  end if;
end $$;

commit;

select 'batches' as item, count(*)::text as detail from public.batches
union all
select 'exams', count(*)::text from public.exams
union all
select 'subject_batches', count(*)::text from public.subject_batches;
